name: mibi_processing
channels:
  - defaults
dependencies:
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - scikit-image
  - jupyterlab
  - openpyxl
  - tifffile
  - matplotlib
  - seaborn
  - py-opencv
  - pip
  - statsmodels
  - numba
  - pytables
  - pytorch::pytorch
  - pytorch::torchvision
  - conda-forge::python-igraph
  - conda-forge::leidenalg
  - pip:
    - mat73
    - medpy
    - pytorch-msssim
    - scanpy
    - FlowGrid
    - PyWavelets
